import { StyleSheet } from 'react-native';
import globalColours, {
  backgroundColour,
  accentColour,
  defaultFont,
} from '../globalColours';

module.exports = StyleSheet.create({
  titleText: {
    color: 'black',
    padding: 10,
    fontSize: 24,
    fontFamily: globalColours.defaultFont,
    alignSelf: 'center',
    fontWeight: 'bold',
    marginTop: '18%',
  },
  defaultSpacedText: {
    alignSelf: 'center',
    fontFamily: '',
    color: 'black',
    fontSize: 16,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  userTextInput: {
    alignSelf: 'center',
    padding: 5,
    margin: 10,
    borderColor: 'black',
    borderWidth: 2,
    height: '8%',
    width: '85%',
    fontWeight: '200',
    color: globalColours.light,
  },
  pressableButton: {
    alignSelf: 'center',
    backgroundColor: globalColours.lightSeaGreen,
    margin: 10,
    padding: 10,
    width: '85%',
    height: '8%',
    alignItems: 'center',
    textButton: {
      color: globalColours.light,
      fontSize: 16,
    },
  },
  checkBox: {
    alignSelf: 'center',
    width: '8%',
    fontSize: 16,
    color: 'black',
  },
  signInWith: {
    width: '100%',
    height: '8%',
    marginTop: '5%',
    marginBottom: '5%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  smallDivider: {
    backgroundColor: globalColours.lightGray,
    width: '21%',
    height: 2,
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'baseline',
    marginLeft: 5,
    marginRight: 10,
  },
  socialMediaButton: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  socialMediaIcon: {
    width: 48,
    height: 48,
  },
});
